//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.0.
// 
using System.Xml.Serialization;
using System.IO;
using System;


/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public class COMPUTER {
    
    /// <remarks/>
    public string HARDDRIVE;
    
    /// <remarks/>
    public string GRAPHICSCARD;
    
    /// <remarks/>
    public string SOUNDCARD;
}

/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute("NewDataSet", Namespace="", IsNullable=false)]
public class NewDataSet
 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("COMPUTER")]
    public COMPUTER[] Items;

	
}

public class newMain
{
	static void Main()
	{
		XmlSerializer xs = new XmlSerializer(typeof(COMPUTER));
		COMPUTER cmp = (COMPUTER)xs.Deserialize(File.Open("..\\..\\computer.xml", FileMode.Open));
		Console.WriteLine("Graphics card is: {0}", cmp.GRAPHICSCARD);

	}

}
